function(bithacks_add_test name)
  add_executable(${name} ${name}.cpp)
  target_link_libraries(${name} PRIVATE bithacks)
  add_test(NAME ${name} COMMAND ${name})
endfunction()

bithacks_add_test(test_sign)
bithacks_add_test(test_abs)
bithacks_add_test(test_minmax)
bithacks_add_test(test_power_of_two)
bithacks_add_test(test_sign_extend)
bithacks_add_test(test_conditional)
bithacks_add_test(test_popcount)
bithacks_add_test(test_parity)
bithacks_add_test(test_swap)
bithacks_add_test(test_reverse)
bithacks_add_test(test_modulus)
bithacks_add_test(test_log2)
bithacks_add_test(test_trailing_zeros)
bithacks_add_test(test_round_power2)
bithacks_add_test(test_interleave)
bithacks_add_test(test_byte_test)
bithacks_add_test(test_next_permutation)
